apiVersion: batch/v1
kind: CronJob
metadata:
  name: wazuh-metrics-fetch
  namespace: site-a
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetcher
            image: nisou624/wazuh-metrics-fetcher:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: hostname
                value: "https://wazuh"
              - name: API_PORT
                value: "55000"
              - name: pushgateway
                value: "http://prometheus-prometheus-pushgateway.monitoring.svc.itm.local:9091"
              - name: username 
                valueFrom:
                  secretKeyRef:
                    name: wazuh-api-cred
                    key: username
              - name: password
                valueFrom:
                  secretKeyRef:
                    name: wazuh-api-cred
                    key: password

          restartPolicy: OnFailure
